<?php

// 'false' blocks new payments, it will still process old payment reports
// to block processing of payment reports edit $stripe_server_name
$stripe_active = false;

/*
 * payments code use 'account ID' and file on HDD to make sure that payments are not duplicated
 * stripe.com reports each payment to all 'endpoints' configured in panel
 * if someone hosts more than 1 OTS [2+ endpoints on stripe.com],
 * it would add points 'to account ID X' on all hosted OTSes - duplicate points
 *
 * 'server_name' is used to make 'other OTSes' (other acc. makers) skip payments not generated by given acc. maker
 */
$stripe_server_name = 'Ocebra';
$stripe_return_url = 'https://127.0.0.1/?subtopic=points';

$stripe_secret_key = 'sk_test_QWEQWEQWE123';
$stripe_endpoint_secret = 'whsec_ASDASDAS123';

$stripe_coin = 'AUD';

$stripe_payments = [
    [
        'money_amount' => '12.50',
        'money_currency' => $stripe_coin,
        'premium_points' => 250,
        'name' => '250 '. $stripe_server_name .' coins.',
        'price_id' => 'https://buy.stripe.com/test_aEUaGj5jE4B5bC07ss',
        'image' => 'https://static.tibia.com/images/payment/serviceid_193_transferable.png',
    ],
    [
        'money_amount' => '35.63',
        'money_currency' => $stripe_coin,
        'premium_points' => 750,
        'name' => '750 '. $stripe_server_name .' coins.',
        'price_id' => 'https://buy.stripe.com/test_aEUaGj5jE4B5bC07ss',
        'image' => 'https://static.tibia.com/images/payment/serviceid_194_transferable.png',
    ],
    [
        'money_amount' => '67.50',
        'money_currency' => $stripe_coin,
        'premium_points' => 1500,
        'name' => '1500 '. $stripe_server_name .' coins.',
        'price_id' => 'https://buy.stripe.com/test_aEUaGj5jE4B5bC07ss',
        'image' => 'https://static.tibia.com/images/payment/serviceid_195_transferable.png',
    ],
    [
        'money_amount' => '127.50',
        'money_currency' => $stripe_coin,
        'premium_points' => 3000,
        'name' => '3000 '. $stripe_server_name .' coins.',
        'price_id' => 'https://buy.stripe.com/test_aEUaGj5jE4B5bC07ss',
        'image' => 'https://static.tibia.com/images/payment/serviceid_196_transferable.png',
    ],
    [
        'money_amount' => '180.00',
        'money_currency' => $stripe_coin,
        'premium_points' => 4500,
        'name' => '4500 '. $stripe_server_name .' coins.',
        'price_id' => 'https://buy.stripe.com/test_aEUaGj5jE4B5bC07ss',
        'image' => 'https://static.tibia.com/images/payment/serviceid_197_transferable.png',
    ],
    [
        'money_amount' => '375.00',
        'money_currency' => $stripe_coin,
        'premium_points' => 10000,
        'name' => '10000 '. $stripe_server_name .' coins.',
        'price_id' => 'https://buy.stripe.com/test_aEUaGj5jE4B5bC07ss',
        'image' => 'https://static.tibia.com/images/payment/serviceid_198_transferable.png',
    ],
];